name: Build and Release Plugin ZIP

on:
  push:
    # Trigger the workflow only on tag pushes
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up PHP (you can specify the version you need, such as PHP 8.0 or 8.1)
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, zip

      # Step 3: Debug GITHUB_REF
      - name: Debug GITHUB_REF
        run: echo "GITHUB_REF is $GITHUB_REF"

      # Step 4: Create the plugin ZIP file
      - name: Create plugin ZIP
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG_VERSION=${GITHUB_REF##*/}  # Extract version from tag
          echo "Tag version is $TAG_VERSION"
          mkdir -p release  # Create a directory for the release package
          zip -r release/wp-api-yoast-update-${TAG_VERSION}.zip . -x ".git/*" -x ".github/*" -x "README.md" -x "LICENSE"

      # Step 5: Upload the ZIP file as a release artifact
      - name: Upload ZIP as release artifact
        uses: actions/upload-artifact@v4
        with:
          name: wp-api-yoast-update.zip
          path: release/wp-api-yoast-update-${TAG_VERSION}.zip

      # Step 6: Create a GitHub Release (only if a tag is pushed)
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: release/wp-api-yoast-update-${TAG_VERSION}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
