name: Build and Release Plugin ZIP

on:
  push:
    # Trigger the workflow on push to the main branch or any tag
    branches:
      - main
    tags:
      - '[0-9]{14}[a-z]?'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up PHP (you can specify the version you need, such as PHP 8.0 or 8.1)
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, zip

      # Step 3: Create the plugin ZIP file
      - name: Create plugin ZIP
        run: |
          zip -r "wp-api-yoast-update-${GITHUB_REF##*/}.zip" . -x ".git/*" -x ".github/*" -x "README.md" -x "LICENSE"
          # Adjust exclusions as needed (e.g., exclude .git or .github directories)

      # Step 4: Upload the ZIP file as a release artifact
      - name: Upload ZIP as release artifact
        uses: actions/upload-artifact@v2
        with:
          name: wp-api-yoast-update.zip
          path: wp-api-yoast-update-${GITHUB_REF##*/}.zip

      # Step 5: Create a GitHub Release (only if a tag is pushed)
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: wp-api-yoast-update-${GITHUB_REF##*/}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
