name: Build and Attach Plugin ZIP

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  zip-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set plugin slug
        id: vars
        run: echo "PLUGIN_SLUG=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV

      - name: Create ZIP file
        run: |
          zip -r $PLUGIN_SLUG.zip . \
            -x ".git/*" ".github/*" "tests/*" "vendor/*" "*.zip"

      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.PLUGIN_SLUG }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PLUGIN_SLUG: ${{ env.PLUGIN_SLUG }}
